name: Docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "doc/"
    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v3
      with:
        name: DocumentationHTML
        path: doc/_build/html/      
    # Publish built docs to gh-pages branch.
    # ===============================
    - name: Commit documentation changes
      run: |
        git clone https://github.com/brendanc490/WebVR-Test-Patterns.git --branch gh-pages --single-branch gh-pages
        mkdir -p gh-pages/doc
        cp -r doc/_build/html/* gh-pages/doc
        cp index.html gh-pages
        cp style.css gh-pages
        cp updatedStyle.css gh-pages
        mkdir -p  gh-pages/Compatibility
        cp -r Compatibility/* gh-pages/Compatibility
        mkdir -p  gh-pages/Custom
        cp -r Custom/* gh-pages/Custom
        mkdir -p  gh-pages/Hardcoded-Tests
        cp -r Hardcoded-Tests/* gh-pages/Hardcoded-Tests
        mkdir -p  gh-pages/Image-Based-Tests
        cp -r Image-Based-Tests/* gh-pages/Image-Based-Tests
        mkdir -p  gh-pages/Images
        cp -r Images/* gh-pages/Images
        mkdir -p  gh-pages/TCA
        cp -r TCA/* gh-pages/TCA
        mkdir -p  gh-pages/lib
        cp -r lib/* gh-pages/lib
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
